import type { PortfolioData } from '@/types'

export const sampleData: PortfolioData = {
  stocks: [
    {
      id: 'stock-1',
      category: 'stock',
      code: '7203.T',
      name: 'トヨタ自動車',
      market: 'JP',
      shares: 100,
      buyPrice: 2500,
      currentPrice: null,
      annualDividend: 60,
      alertDropPct: 10,
      alertYieldBelow: 3,
      sector: '一般消費財',
    },
    {
      id: 'stock-2',
      category: 'stock',
      code: '8058.T',
      name: '三菱商事',
      market: 'JP',
      shares: 200,
      buyPrice: 3800,
      currentPrice: null,
      annualDividend: 150,
      alertDropPct: 10,
      alertYieldBelow: 3,
      sector: '資本財',
    },
    {
      id: 'stock-3',
      category: 'stock',
      code: 'AAPL',
      name: 'Apple Inc.',
      market: 'US',
      shares: 10,
      buyPrice: 150,
      currentPrice: null,
      annualDividend: 0.96,
      alertDropPct: 10,
      alertYieldBelow: 1,
      sector: '情報技術',
    },
  ],
  bonds: [
    {
      id: 'bond-1',
      category: 'bond' as const,
      name: '利付国債10年',
      issuer: '日本国',
      bondType: '国債' as const,
      faceValue: 1000000,
      quantity: 1,
      couponRate: 0.8,
      purchasePrice: 99.5,
      currentPrice: 99.8,
      maturityDate: '2034-03-20',
      currency: 'JPY' as const,
    },
  ],
  cash: [
    {
      id: 'cash-1',
      category: 'cash',
      name: '普通預金',
      amount: 3000000,
      currency: 'JPY',
      institution: 'みずほ銀行',
      annualRate: 0.001,
      note: '生活費口座',
    },
    {
      id: 'cash-2',
      category: 'cash',
      name: '米ドル預金',
      amount: 5000,
      currency: 'USD',
      institution: 'SBI証券',
      annualRate: 4.5,
      note: '外貨預金',
    },
  ],
  realestate: [
    {
      id: 'realestate-1',
      category: 'realestate',
      name: '名古屋マンション',
      location: '愛知県名古屋市',
      purchasePrice: 25000000,
      currentValue: 28000000,
      monthlyRent: 80000,
      mortgageBalance: 15000000,
      note: '区分マンション投資',
    },
  ],
  cryptos: [
    {
      id: 'crypto-1',
      category: 'crypto',
      symbol: 'BTC-JPY',
      name: 'Bitcoin',
      amount: 0.5,
      buyPrice: 8000000,
      currentPrice: null,
      alertDropPct: 20,
    },
    {
      id: 'crypto-2',
      category: 'crypto',
      symbol: 'ETH-JPY',
      name: 'Ethereum',
      amount: 2,
      buyPrice: 400000,
      currentPrice: null,
      alertDropPct: 20,
    },
  ],
}
